version: '2'

networks:
  cicdnetwork:
    driver: bridge

#volumes:
#  artifactory-data:
#  jenkins-data: 

services:
  jenkins:
    container_name: jenkinslts
    image: 'jenkins/jenkins:lts'
    ports:
      - '8080:8080'
      - '5000:5000'
      - '50000:50000'
    networks:
      - cicdnetwork
    volumes:
        - '/home/acam/Public/docker/jenkins/jenkins_home:/var/jenkins_home'
    depends_on:
      - sonarqube
      - artifactory
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
     - "9000:9000"
     - "9092:9092"
    networks:
      - cicdnetwork
  artifactory:
    container_name: artifactory
    image: docker.bintray.io/jfrog/artifactory-oss:latest 
    ports:
     - "8081:8081"
    networks:
      - cicdnetwork
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
#    volumes:
#     - artifactory-data:/artifactory-data


